service: squadup-app-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: DeleteItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  handler: create.main
  events:
    - http:
      path: squadup
      method: post
      cors: false
      authorizer: aws_iam
